[[language]]
name = "markdown"
language-servers = ["marksman", "mdpls"]

[language-server.mdpls]
command = "/home/manuel/.cargo/bin/mdpls"
config = { markdown.preview.auto = true }

[[language]]
name = "rust"
auto-format = true
#
[language-server.rust-analyzer]
config = { checkOnSave = { command = "clippy" }, cargo = { allFeatures = true, features = "all" }}
